// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/pSnehanshu/govatar/ent/avatar"
	"github.com/pSnehanshu/govatar/ent/email"
	"github.com/pSnehanshu/govatar/ent/predicate"
)

// AvatarQuery is the builder for querying Avatar entities.
type AvatarQuery struct {
	config
	ctx        *QueryContext
	order      []avatar.OrderOption
	inters     []Interceptor
	predicates []predicate.Avatar
	withEmail  *EmailQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AvatarQuery builder.
func (aq *AvatarQuery) Where(ps ...predicate.Avatar) *AvatarQuery {
	aq.predicates = append(aq.predicates, ps...)
	return aq
}

// Limit the number of records to be returned by this query.
func (aq *AvatarQuery) Limit(limit int) *AvatarQuery {
	aq.ctx.Limit = &limit
	return aq
}

// Offset to start from.
func (aq *AvatarQuery) Offset(offset int) *AvatarQuery {
	aq.ctx.Offset = &offset
	return aq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aq *AvatarQuery) Unique(unique bool) *AvatarQuery {
	aq.ctx.Unique = &unique
	return aq
}

// Order specifies how the records should be ordered.
func (aq *AvatarQuery) Order(o ...avatar.OrderOption) *AvatarQuery {
	aq.order = append(aq.order, o...)
	return aq
}

// QueryEmail chains the current query on the "email" edge.
func (aq *AvatarQuery) QueryEmail() *EmailQuery {
	query := (&EmailClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(avatar.Table, avatar.FieldID, selector),
			sqlgraph.To(email.Table, email.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, avatar.EmailTable, avatar.EmailColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Avatar entity from the query.
// Returns a *NotFoundError when no Avatar was found.
func (aq *AvatarQuery) First(ctx context.Context) (*Avatar, error) {
	nodes, err := aq.Limit(1).All(setContextOp(ctx, aq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{avatar.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aq *AvatarQuery) FirstX(ctx context.Context) *Avatar {
	node, err := aq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Avatar ID from the query.
// Returns a *NotFoundError when no Avatar ID was found.
func (aq *AvatarQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = aq.Limit(1).IDs(setContextOp(ctx, aq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{avatar.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aq *AvatarQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := aq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Avatar entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Avatar entity is found.
// Returns a *NotFoundError when no Avatar entities are found.
func (aq *AvatarQuery) Only(ctx context.Context) (*Avatar, error) {
	nodes, err := aq.Limit(2).All(setContextOp(ctx, aq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{avatar.Label}
	default:
		return nil, &NotSingularError{avatar.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aq *AvatarQuery) OnlyX(ctx context.Context) *Avatar {
	node, err := aq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Avatar ID in the query.
// Returns a *NotSingularError when more than one Avatar ID is found.
// Returns a *NotFoundError when no entities are found.
func (aq *AvatarQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = aq.Limit(2).IDs(setContextOp(ctx, aq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{avatar.Label}
	default:
		err = &NotSingularError{avatar.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aq *AvatarQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := aq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Avatars.
func (aq *AvatarQuery) All(ctx context.Context) ([]*Avatar, error) {
	ctx = setContextOp(ctx, aq.ctx, "All")
	if err := aq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Avatar, *AvatarQuery]()
	return withInterceptors[[]*Avatar](ctx, aq, qr, aq.inters)
}

// AllX is like All, but panics if an error occurs.
func (aq *AvatarQuery) AllX(ctx context.Context) []*Avatar {
	nodes, err := aq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Avatar IDs.
func (aq *AvatarQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if aq.ctx.Unique == nil && aq.path != nil {
		aq.Unique(true)
	}
	ctx = setContextOp(ctx, aq.ctx, "IDs")
	if err = aq.Select(avatar.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aq *AvatarQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := aq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aq *AvatarQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, aq.ctx, "Count")
	if err := aq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, aq, querierCount[*AvatarQuery](), aq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (aq *AvatarQuery) CountX(ctx context.Context) int {
	count, err := aq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aq *AvatarQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, aq.ctx, "Exist")
	switch _, err := aq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (aq *AvatarQuery) ExistX(ctx context.Context) bool {
	exist, err := aq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AvatarQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aq *AvatarQuery) Clone() *AvatarQuery {
	if aq == nil {
		return nil
	}
	return &AvatarQuery{
		config:     aq.config,
		ctx:        aq.ctx.Clone(),
		order:      append([]avatar.OrderOption{}, aq.order...),
		inters:     append([]Interceptor{}, aq.inters...),
		predicates: append([]predicate.Avatar{}, aq.predicates...),
		withEmail:  aq.withEmail.Clone(),
		// clone intermediate query.
		sql:  aq.sql.Clone(),
		path: aq.path,
	}
}

// WithEmail tells the query-builder to eager-load the nodes that are connected to
// the "email" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AvatarQuery) WithEmail(opts ...func(*EmailQuery)) *AvatarQuery {
	query := (&EmailClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withEmail = query
	return aq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Avatar.Query().
//		GroupBy(avatar.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (aq *AvatarQuery) GroupBy(field string, fields ...string) *AvatarGroupBy {
	aq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AvatarGroupBy{build: aq}
	grbuild.flds = &aq.ctx.Fields
	grbuild.label = avatar.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Avatar.Query().
//		Select(avatar.FieldCreatedAt).
//		Scan(ctx, &v)
func (aq *AvatarQuery) Select(fields ...string) *AvatarSelect {
	aq.ctx.Fields = append(aq.ctx.Fields, fields...)
	sbuild := &AvatarSelect{AvatarQuery: aq}
	sbuild.label = avatar.Label
	sbuild.flds, sbuild.scan = &aq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AvatarSelect configured with the given aggregations.
func (aq *AvatarQuery) Aggregate(fns ...AggregateFunc) *AvatarSelect {
	return aq.Select().Aggregate(fns...)
}

func (aq *AvatarQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range aq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, aq); err != nil {
				return err
			}
		}
	}
	for _, f := range aq.ctx.Fields {
		if !avatar.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aq.path != nil {
		prev, err := aq.path(ctx)
		if err != nil {
			return err
		}
		aq.sql = prev
	}
	return nil
}

func (aq *AvatarQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Avatar, error) {
	var (
		nodes       = []*Avatar{}
		_spec       = aq.querySpec()
		loadedTypes = [1]bool{
			aq.withEmail != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Avatar).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Avatar{config: aq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := aq.withEmail; query != nil {
		if err := aq.loadEmail(ctx, query, nodes, nil,
			func(n *Avatar, e *Email) { n.Edges.Email = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (aq *AvatarQuery) loadEmail(ctx context.Context, query *EmailQuery, nodes []*Avatar, init func(*Avatar), assign func(*Avatar, *Email)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Avatar)
	for i := range nodes {
		fk := nodes[i].EmailID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(email.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "email_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (aq *AvatarQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aq.querySpec()
	_spec.Node.Columns = aq.ctx.Fields
	if len(aq.ctx.Fields) > 0 {
		_spec.Unique = aq.ctx.Unique != nil && *aq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, aq.driver, _spec)
}

func (aq *AvatarQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(avatar.Table, avatar.Columns, sqlgraph.NewFieldSpec(avatar.FieldID, field.TypeUUID))
	_spec.From = aq.sql
	if unique := aq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if aq.path != nil {
		_spec.Unique = true
	}
	if fields := aq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, avatar.FieldID)
		for i := range fields {
			if fields[i] != avatar.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if aq.withEmail != nil {
			_spec.Node.AddColumnOnce(avatar.FieldEmailID)
		}
	}
	if ps := aq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aq *AvatarQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aq.driver.Dialect())
	t1 := builder.Table(avatar.Table)
	columns := aq.ctx.Fields
	if len(columns) == 0 {
		columns = avatar.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aq.sql != nil {
		selector = aq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aq.ctx.Unique != nil && *aq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range aq.predicates {
		p(selector)
	}
	for _, p := range aq.order {
		p(selector)
	}
	if offset := aq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AvatarGroupBy is the group-by builder for Avatar entities.
type AvatarGroupBy struct {
	selector
	build *AvatarQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (agb *AvatarGroupBy) Aggregate(fns ...AggregateFunc) *AvatarGroupBy {
	agb.fns = append(agb.fns, fns...)
	return agb
}

// Scan applies the selector query and scans the result into the given value.
func (agb *AvatarGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, agb.build.ctx, "GroupBy")
	if err := agb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AvatarQuery, *AvatarGroupBy](ctx, agb.build, agb, agb.build.inters, v)
}

func (agb *AvatarGroupBy) sqlScan(ctx context.Context, root *AvatarQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(agb.fns))
	for _, fn := range agb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*agb.flds)+len(agb.fns))
		for _, f := range *agb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*agb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := agb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AvatarSelect is the builder for selecting fields of Avatar entities.
type AvatarSelect struct {
	*AvatarQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (as *AvatarSelect) Aggregate(fns ...AggregateFunc) *AvatarSelect {
	as.fns = append(as.fns, fns...)
	return as
}

// Scan applies the selector query and scans the result into the given value.
func (as *AvatarSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, as.ctx, "Select")
	if err := as.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AvatarQuery, *AvatarSelect](ctx, as.AvatarQuery, as, as.inters, v)
}

func (as *AvatarSelect) sqlScan(ctx context.Context, root *AvatarQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(as.fns))
	for _, fn := range as.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*as.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := as.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
